### ISSUE TITLE
OpenAPI spec minItems: 1 is not respected

### ISSUE THREAD

**Issue by nats** [binarylane/binarylane-cli#37]
e.g.

```yaml
AdvancedFirewallRule:
      required:
        - action
        - destination_addresses
        - protocol
        - source_addresses
      type: object
      properties:
        source_addresses:
          minItems: 1
          type: array
          items:
            type: string
          description: The source addresses to match for this rule. Each address may be an individual IPv4 address or a range in IPv4 CIDR notation.
          x-cli-format: 1
```

CLI incorrectly accepts a zero-entry list , e.g. here --source-addresses is empty list `bl  server action change-advanced-firewall-rules $ID +rule --source-addresses --destination-addresses 127.0.0.1 --protocol all --action accept`
